-- Supabase Auth setup (Dashboard — reference only)
--
-- REQUIRED: Disable email confirmation so users sign in immediately after sign-up.
--   Authentication → Providers → Email → turn OFF "Confirm email"
--
-- After sign-up or sign-in, the site sends users to the homepage (unless ?r= is set,
-- e.g. when booking a showing).
--
-- =============================================================================
-- LEGACY USERS (signed up while confirmation was ON)
-- =============================================================================
-- They remain unconfirmed until you unlock them once:
--
-- Option A: Authentication → Users → select user → ⋮ → Confirm user
--
-- Option B (SQL Editor):
--   update auth.users
--   set
--     email_confirmed_at = timezone('utc', now()),
--     confirmed_at = timezone('utc', now())
--   where email = 'ctamay323@gmail.com';
--
-- =============================================================================
-- URL Configuration (still used for password reset)
-- =============================================================================
-- Site URL:
--   https://astridbonoan.github.io/tamay_Enterprise_construction.io
-- Redirect URLs:
--   https://astridbonoan.github.io/tamay_Enterprise_construction.io/m/login/**
